# Generated by Django 5.2.4 on 2025-07-14 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='teacher_id',
            new_name='teacher',
        ),
    ]
