# Generated by Django 5.2.4 on 2025-07-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_rename_teacher_id_student_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
